version: '3'

services:
  project:
    restart: always
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"